project:
  type: website

website:
  navbar:
    title: false
    left:
      - icon: house
        href: /index.html
    right:
      - text: "Destra e sinistra"
        href: /dxsx/index.html
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css

editor: visual

